name: Reusable Build & Push (SemVer)

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      context:
        required: true
        type: string
    secrets:
      REGISTRY_USER:
        required: true
      REGISTRY_PASS:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed for tags

      - name: Log in to registry
        run: echo "${{ secrets.REGISTRY_PASS }}" | docker login ghcr.io -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "${{ inputs.service }}-"
          fetch_all_tags: true

      - name: Build Docker image
        run: |
          VERSION=${{ steps.tag_version.outputs.new_tag }}
          VERSION=${VERSION#${{ inputs.service }}-} # remove service prefix
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          docker build -t ghcr.io/${{ github.repository }}/${{ inputs.service }}:$VERSION \
                       -t ghcr.io/${{ github.repository }}/${{ inputs.service }}:latest \
                       -f ${{ inputs.dockerfile }} ${{ inputs.context }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/${{ inputs.service }}:$VERSION
          docker push ghcr.io/${{ github.repository }}/${{ inputs.service }}:latest
